name: Artifacts

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  amd64:
    name: Build binaries

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.14.x]
        architecture: [amd64, arm, arm64]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOARCH=${{ matrix.architecture }} make build

      - name: Upload boltzd
        uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.architecture }}
          path: boltzd

      - name: Upload boltz-cli
        uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.architecture }}
          path: boltz-cli
