name: Artifacts

on:
  push:
    branches:
      - master
      # TODO: remove after initial testing
      - windows-darwin-artifacts

    tags:
      - v*

jobs:
  build:
    name: Build binaries

    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.15.x ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install C cross compilers
        run: sudo apt-get update && sudo apt-get -y install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi gcc-mingw-w64

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fetch dependencies
        run: go mod vendor

      - name: Build
        run: make binaries

      - name: Upload Linux AMD64 artifact
        uses: actions/upload-artifact@v2
        with:
          name: boltz-lnd-linux-amd64.zip
          path: binaries/linux-amd64/

      - name: Upload Linux ARM64 artifact
        uses: actions/upload-artifact@v2
        with:
          name: boltz-lnd-linux-arm64.zip
          path: binaries/linux-arm64/

      - name: Upload Linux ARM artifact
        uses: actions/upload-artifact@v2
        with:
          name: boltz-lnd-linux-arm.zip
          path: binaries/linux-arm/

      - name: Upload Windows AMD64 artifact
        uses: actions/upload-artifact@v2
        with:
          name: boltz-lnd-windows-amd64.zip
          path: binaries/windows-amd64/
