name: Artifacts

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  amd64:
    name: Build AMD64 binaries

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.14.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Upload boltzd
        uses: actions/upload-artifact@v1
        with:
          name: linux-amd64
          path: boltzd

      - name: Upload boltz-cli
        uses: actions/upload-artifact@v1
        with:
          name: linux-amd64
          path: boltz-cli

  arm:
    name: Build ARM binaries

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.14.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOARCH=arm make build

      - name: Upload boltzd
        uses: actions/upload-artifact@v1
        with:
          name: linux-arm
          path: boltzd

      - name: Upload boltz-cli
        uses: actions/upload-artifact@v1
        with:
          name: linux-arm
          path: boltz-cli

  arm64:
    name: Build ARM64 binaries

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.14.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOARCH=arm64 make build

      - name: Upload boltzd
        uses: actions/upload-artifact@v1
        with:
          name: linux-arm64
          path: boltzd

      - name: Upload boltz-cli
        uses: actions/upload-artifact@v1
        with:
          name: linux-arm64
          path: boltz-cli